import { type NextPage } from 'next';
import Head from 'next/head';
import { useSession } from 'next-auth/react';

import { StarterPage, HiringDashboard } from '../components';
import { classNames } from '../utils/classNames';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
  const { data: sessionData, status } = useSession();
  const router = useRouter();
  const isFilteredByCompany = router.asPath.includes('?filteredBy=');

  if(status === 'loading') return <div>Loading...</div>

  return (
    <>
      <Head>
        <title>Hiring Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={classNames(
          sessionData
            ? 'min-h-full'
            : 'flex items-center justify-center bg-gray-100'
        )}
      >
        {sessionData ? (
          <HiringDashboard isFiltered={isFilteredByCompany} />
        ) : (
          <StarterPage />
        )}
      </div>
    </>
  );
};

export default Home;
