import { type NextPage } from 'next';
import Head from 'next/head';
import { useSession } from 'next-auth/react';

import Navigation from '../components/Navigation';
import { classNames } from '../utils/classNames';
import HiringDashboard from '../components/HiringDashboard';
import StarterPage from '../components/StarterPage';

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Hiring Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={classNames(
          sessionData
            ? 'min-h-full'
            : 'flex items-center justify-center bg-gray-100'
        )}
      >
        {sessionData ? <HiringDashboard /> : <StarterPage />}
      </div>
    </>
  );
};

export default Home;
